languageCode = "en"
languageName = "English"
weight = 1
title = ""

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/ag-cakes-icon.png"
  description = ""

[params.author]
  name = ""
  headline = ""
  bio = ""
  links = []